name: example
description: Example
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

dependencies:
  exceptions:
    path: ../
  http: ^1.1.0
