name: exceptions
description: This package helps catching and handling occuring Exceptions by producing a single result that either contains an error or value.
version: 0.1.0
repository: https://github.com/FaFre/exceptions

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  fast_equatable: ^0.9.0
