name: exceptions
description: This package assists in catching and handling exceptions that occur, producing a single result that contains either an error or a value.
version: 0.5.0
repository: https://github.com/FaFre/exceptions

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lint: ^2.3.0
  test: ^1.16.0
