name: exceptions
description: This package helps catching and handling occuring Exceptions by producing a single result that either contains an error or value.
version: 0.1.0
repository: https://github.com/FaFre/exceptions

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

dependencies:
  fast_equatable: ^1.0.0
